version: "2.4"

services:
  web:
    platform: linux/arm64/v8
    image: ghcr.io/nikwebr/checkokay:latest
    container_name: next
    build:
      context: .
      dockerfile: ./apps/next/Dockerfile
    restart: always
    ports:
      - 3000:3000