/** @jsxImportSource react */

import 'app/global.css';

import { StylesProvider } from './styles-provider'
import { Provider } from 'app/provider'
import 'setimmediate'
import 'raf/polyfill'

export const metadata = {
    title: 'Create Solito App',
    description: 'Generated by create Solito app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                <StylesProvider>
                    <Provider>{children}</Provider>
                </StylesProvider>
            </body>
        </html>
    )
}
