name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - name: install cloudflared
        run: |
          curl -L https://pkg.cloudflare.com/cloudflare-main.gpg | sudo tee /usr/share/keyrings/cloudflare-archive-keyring.gpg >/dev/null
          echo "deb [signed-by=/usr/share/keyrings/cloudflare-archive-keyring.gpg] https://pkg.cloudflare.com/cloudflared $(lsb_release -cs) main" | sudo tee  /etc/apt/sources.list.d/cloudflared.list
          sudo apt update
          sudo apt-get install cloudflared
          cloudflared --version
      - name: Generate SSH Config
        id: ssh
        shell: bash
        run: |
          eval $(ssh-agent)
          mkdir -p ~/.ssh
          cat >> ~/.ssh/config << EOF
          Host ${{ vars.DEPLOY_SSH_ADDRESS }}
            HostName ${{ vars.DEPLOY_SSH_ADDRESS }}
            StrictHostKeyChecking no
            ProxyCommand /usr/local/bin/cloudflared access ssh --id ${{ secrets.CLOUDFLARED_CLIENT_ID }} --secret ${{ secrets.CLOUDFLARED_CLIENT_SECRET }} --hostname %h
          EOF
      - uses: webfactory/ssh-agent@v0.8.0
        with: 
            ssh-private-key: ${{ secrets.SSH_KEY }}
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: sudo docker-compose build
      - name: Publish image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | sudo docker login ghcr.io -u $ --password-stdin
          sudo docker push ${{ vars.IMAGE_NAME }}
      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: ssh://dokku@${{ vars.DEPLOY_SSH_ADDRESS }}:22/${{ vars.DOKKU_APP_NAME }}
          ssh_private_key: ${{ secrets.SSH_KEY }}
          deploy_docker_image: ${{ vars.IMAGE_NAME }}
      - name: Database migration
        run: |
          ssh ubuntu@${{ vars.DEPLOY_SSH_ADDRESS }} dokku run ${{ vars.DOKKU_APP_NAME }} /bin/sh -c 'cd packages/db; node dist/migrate.js'
